name: Nightly Docker Image
on:
  schedule:
    - cron: "13 12 * * *"
  workflow_dispatch:
jobs:
  push_steamcmd_to_registry:
    name: Push steamcmd Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push steamcmd
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: base-images/steamcmd
          push: true
          tags: dedicatedgames/steamcmd:latest
  push_valheim_to_registry:
    name: Push valheim Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push valheim
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: valheim
          push: true
          tags: dedicatedgames/valheim:latest
      # This is currently not supported using access tokens, see: https://github.com/docker/roadmap/issues/115
      # -
      #   name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: dedicatedgames/steamcmd
      #     readme-filepath: base-images/steamcmd/README.md
